Dockerfile
go/Dockerfile

This updates the Protocol Buffer compiler to use 3.4.1.  It also includes the standard Google API's protobuf definitions in the include path. This allows you to import definitions such as:
```proto
import "googleapis/google/rpc/status.proto";
```
Includes an update to the Go container to use the latest version of the gRPC generator.

Update protoc to 3.4 and grpc in the Go container

---

README.md
all/entrypoint.sh
test.sh
test/include.proto
test/test.proto

The previous protoc-all container only supported a single proto input file. This method supports a directory option, which will generate code for all proto files in a directory (one level only), with gateway support.

Support proto-discovery within a directory for all container

---

all/entrypoint.sh
test.sh

grpc-gateway generation is now golang specific.
gateway files are generated in the same directory as the protobufs, which is required for imports to work.

Fixes to grpc-gateway generation

---

all/entrypoint.sh
all/test.sh

Also added __init__.py files so that generated module can be imported.
This is because python cannot (easily) import from directories with
a dash in them.

Made python use underscores instead of dashes

---

all/entrypoint.sh
all/test.sh

The node grpc plugin currently has a hard coded assumption that the message file
to go with a certain service file is "../foo/foo_pb.js". This is not always the
case, but for now we try to ensure the --js_out argument is set to match what
the grpc plugin expects.

Add support to generate nodejs output.

---

gwy/templates/config.yaml.tmpl
gwy/templates/main.go.tmpl
gwy/test.sh

By specifying proxy.api-prefix, you can have the gateway strip prefixes.
For example, suppose that you have a proto file with the following:
```
option (google.api.http) = {
get: "/v1alpha1/fun"
};
```
If you wanted people to access it at https://example.com/api/v1alpha1/fun you would specify proxy.api-prefix=/api/, and the gateway will do the rest.
Fixes #56

Allow running gateway under directory.

---

gwy/Dockerfile
gwy/templates/main.go.tmpl

The grpc-gateway now sends all headers unmodified to the downstream service as metadata, rather than only those that started with `Grpc-Gateway-`. This will break backward compatibility for anyone who was using that prefix, as the gateway would strip this prefix, however I don't think that anyone was using it yet.
Tested locally, we don't have a great way to test this programmatically yet. It's on my list!
I had the client send a new header `X-My-Header: asdf` and the server set metadata `outbound-header: foobar`, with
```
header := metadata.Pairs("outbound-header", "foobar")
grpc.SendHeader(ctx, header)
```
Client:
```
curl -iv localhost:8000/v1/shelves --header 'X-My-Header: asdf'
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8000 (#0)
> GET /v1/shelves …
```

Forward all headers, not just those starting with Grpc-Gateway-

---

gwy/Makefile
gwy/templates/main.go.tmpl

This is nicer, now if you pass 'Foo', you get metadata 'foo' on the other side.
The only exceptions are:
1. Permanent headers are prefixed with grpcgateway (this is what the gateway does by default).
2. Headers starting with Grpc- are prepended with X-, since Grpc- is a reserved metadata prefix in grpc.

Only prefix permanent headers and reserved headers

---

all/entrypoint.sh

This was defined and immediately overwritten with a newer constant.

Remove duplicated SUPPORTED_LANGUAGES constant

---

all/entrypoint.sh

My team is working on introducing linting of our protobufs. I noticed that `protoc-gen-lint` is being installed in the container:
https://github.com/namely/docker-protoc/blob/32cda135bca79697425b25f67f4aa69ceadfc85a/all/Dockerfile#L39
But it's not being exposed via the entrypoint. This PR adds a flag to enable linting. I've tested this on my project and it's working as I'd expect.
This is available under my dockerhub if you want to test it out:
```
blimmer/protoc-all:1.11-lint
```

Expose linting

---

gwy/templates/main.go.tmpl

When proxing via the Istio Mesh, there's a bug where setting Content-Length in the gRPC metadata really screws with it causing:
```
stream terminated by RST_STREAM with error code: PROTOCOL_ERROR
```

Skip Content-Length header

---

all/entrypoint.sh

I have a use case for the "source-relative" --go-out option. I'd like to add support for this option.

add option for making go paths source_relative

---

README.md
all/Dockerfile
all/Makefile
all/install-protobuf.sh
gwy/Dockerfile
gwy/Makefile

Also include swagger protos in include so you can easily use them in proto files.
@kaimou1357 @mdkess 
It's super weird the way we have to use swagger annotations. If they're in the proto they should be available just like the Google proto types. This includes the swagger annotations proto in the include path for proto so you can use them easier.

Upgrade grpc to 1.14

---

Dockerfile

See uber/prototool#193 which requires ca-certificates and libc6-compat to run the cached protoc on alpine.

add necessary prototool libs

---

gwy/templates/main.go.tmpl

This will make it so request headers are no longer logged by default. To enable header logging you can set:
```
log_headers = true
```

Put header logging behind a config flag

---

gwy/templates/main.go.tmpl

In order to support the standard set of status.Status error details we need to import the google.golang.org/genproto/googleapis/rpc/errdetails package.  This will cause the init() function to be called and register the types in the proto type registry

Import standard error details

---

README.md
gwy/templates/main.go.tmpl
gwy/test.sh

The proposed changes would enable configuring additional headers as part of each http response provided by the grpc-gateway.
It would help with [this](https://namely.atlassian.net/browse/PU-3806) bug by sending 
`Cache-Control: no-cache` in the header.
The env var set in the config map of the service would be in this case:
`ORGUNITSREADER_RESPONSE-HEADERS_CACHE-CONTROL="no-cache"`

Adding option to configure response headers from env vars

---

all/entrypoint.sh
all/install-protobuf.sh
all/test.sh
build.sh
push.sh
variables.sh

The change was introduced in 34c804c3a909a667fc4b7757537b0f1f01a15aea. This has led to some seriously loud noise in our pipeline. To exit on error only the `e` option is needed, so the original goal of the aforementioned commit is still fulfilled.
We've pinned the image back to an older version (the last version that wasn't super verbose was 1.17_0 as far as I can tell).
Even things like the help output are obscured by it:
```
$ docker run --rm namely/protoc-all --help
+ GEN_GATEWAY=false
+ GEN_DOCS=false
+ DOCS_FORMAT=html,index.html
+ LINT=false
+ LINT_CHECKS=
+ SUPPORTED_LANGUAGES=("go" "ruby" "csharp" "java" "python" "objc" "gogo" "php" "node" "web" "cpp")
+ EXTRA_INCLUDES=
+ OUT_DIR=
+ GO_SOURCE_RELATIVE=
+ test 1 -gt 0
+ case "$1" in
+ printUsage
+ echo 'gen-proto generates grpc and …
```

Removed `x` option passed to Bash in scripts causing extreme verbosity in output

---

Dockerfile
all/entrypoint.sh
all/test.sh

This PR is an implementation of the feature request described in https://github.com/namely/docker-protoc/issues/111:
My proposal is to add a `--with-typescript` option to the `node` language that leverages the [ts-protoc-gen](https://github.com/improbable-eng/ts-protoc-gen#readme) plugin to generate TypeScript declaration files (`.d.ts` files) that match the JavaScript output of `protoc --js_out=import_style=commonjs,binary`.
That plugin can also generate service definitions that include TypeScript declarations in the structure required by the [Improbable grpc-web implementation](https://github.com/improbable-eng/grpc-web). This PR doesn't use that feature; I thought if it would be useful to expose it as an option, maybe it would make sense as an option to the `web` language, and could be …

Add TypeScript declaration support using protoc-gen-ts plugin

---

Dockerfile

The new 1.0.4 version generates Typescript files slightly differently than the older version.
https://github.com/grpc/grpc-web/releases/tag/1.0.4

Update protoc-gen-grpc-web from 1.0.3 to 1.0.4

---

Dockerfile
all/entrypoint.sh
all/test.sh

PR #125 added the `--with-typescript` option to generate .d.ts declaration files for node using the ts-protoc-gen plugin, but it didn't generate .d.ts files for gRPC services.
This PR adds support for that, fixing issue #138, by bumping the ts-protoc-gen version from 0.10.0 to 0.11.0 (which includes https://github.com/improbable-eng/ts-protoc-gen/pull/193, introducing the `service=grpc-node` option to generate those .d.ts files).

Generate .d.ts files for node gRPC services

---

.gitattributes

Cloning this repo on Windows will corrupt the line endings without this setting.

Ensure shell scripts use LF

---

README.md

I looked up the actual paths in current dockerfile, and tested with a proto which uses WKTs. The paths are no longer under `/usr`. They are under `/opt`.

Update google paths in readme

---

all/entrypoint.sh

If you specify output directory with "-o" option as absolute and language is python then bash script fall to infinite loop.

fix while loop for output dirs specified as absolute

---

all/entrypoint.sh

This is needed, because there are some [options for csharp codegen](https://developers.google.com/protocol-buffers/docs/reference/csharp-generated#compiler_options) that we're going to need. Specifically, we need to set `base_namespace`, but I feel like this is better than trying to break the individual options out.

Adds support to pass the csharp options to protoc

---

Dockerfile
all/entrypoint.sh

Added support for https://github.com/envoyproxy/protoc-gen-validate to multi-language use cases.

Add support to envoyproxy gRPC validator

---

Dockerfile

"build" container uses alpine tag specified as $alpine ARG, but protoc-all, which is base image of grpc-cli, uses static tag 3.9.
This causes mismatch of C++ dynamic libraries like this:
> docker run namely/grpc-cli:latest
Error relocating /usr/local/bin/grpc_cli: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
This patch fixes Dockerfile to use the same alpine:$alpine for all base images.

Fix base alpine image tag mismatch

---

Dockerfile
all/entrypoint.sh
build.sh
cli/entrypoint.sh

The Swagger module is not available anymore and has been substitute by the OpenAPIv2 one.
This is also fixing the build that is failing at the moment.
See https://github.com/grpc-ecosystem/grpc-gateway/commit/58213a464a0f1368ec047b870c33a4a16e0ccf90

Move from Swagger to OpenAPIv2

---

Dockerfile
all/test.sh

- The build was failing because of an upgrade to protoc-gen-doc that is not compatible.
To solve the problem the protoc-gen-doc module was pinned to the latest version that is compatible.
- Also:
-     Added tests for the relevant flag option
-     Pinned Golang grpc module to match the image's version.

Fix build due to unpinned mismatched version of protoc-gen-doc

---

.github/workflows/grpc_release.yml
README.md

With this change, a new GH release will be created automatically every time we merge a Renovate branch which updated the gRPC version to master.
The branch name is determined in the Renovate configuration file and is referenced in the GH Action workflow file in this PR, so that other type of PRs whether they are created by the Renovate user or any other user, will be ignored.
This will allow us to avoid creating a new release manually after merging.
If and when we automerge the Renovate PRs, the process will be fully automated, i.e every time a new gRPC version is released to github.com/grpc/grpc, the matching docker images artifacts of this repo will be released as well.

Configure automatic grpc releases

---

all/test/all_test.go

- This fixes a bug that caused most of the test cases to not execute.
See https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables
- Also changing the name of the temp dir used in each test case to be based off of the name of the test instead of just the lang.

A fix for test cases that were not executed due to a bug in parallelism

---

all/entrypoint.sh
all/test/all_test.go

Ensure the gateway files are generated according the source_relative settings.
Credit to @vaijab

Generate gateway files according to source-relative flag

---

.github/renovate.json5

This PR will modify https://github.com/namely/docker-protoc/pull/319 (and others like it in the future),
so that it will also update the Go version [here](https://github.com/namely/docker-protoc/blob/master/variables.sh#L9) and [here](https://github.com/namely/docker-protoc/blob/master/.github/renovate.json5#L8).

Update where Renovate updates the Go version

---

.github/renovate.json5

Forgot one more location the Go version should be updated - 
https://github.com/namely/docker-protoc/blob/master/gwy/templates/Dockerfile.tmpl#L4

Renovate  - update the Go version in one more location

---

.github/renovate.json5

The regex in the previous PR was not accurate.
This one works though - tested on my fork https://github.com/ido-namely/docker-protoc/pull/27/files#diff-842c17f24ff78272657d7c5ae75b4bde7c83c0064d9a5efccac10a1a0feeeb10

Fix the Renovate regex for the go upgrade

---

.github/renovate.json5

Also cleaning up:
- no need to group major upgrades of dependencies - it's unlikely we'll have multiple concurrent major release of dependencies and we'd want to be able to review and merge them independently anyway.
- some dependencies were grouped by name but they were already grouped according to their datasource
- some recently added dependencies were not grouped but are grouped now.

Enable automerge for non gRPC minor + patch dependencies

---

Dockerfile
all/test/all_test.go

When PYTHONPATH is empty to start with, it gets set to a value of `:/opt/mypy-protobuf/`. The leading semicolon acts as an empty entry at the beginning of the path list and implies the current working directory. So this can break Python plugins depending on what directory `protoc` is executed in. I've got a snippet below to demonstrate what I mean.
```console
// Printing the default PYTHONPATH, notice the leading semicolon.
tetsuo@Alexs-MacBook-Pro protobuf-specs % docker run --platform linux/amd64 -v ${PWD}:/defs --entrypoint bash namely/protoc-all:latest -c 'echo "$PYTHONPATH"'
:/opt/mypy-protobuf/
// Now do a simple print via the Python interpreter.
tetsuo@Alexs-MacBook-Pro protobuf-specs % docker run --platform linux/amd64 -v ${PWD}:/defs --entrypoint python3 namely/protoc-all:latest …
```

Remove potential leading colon from PYTHONPATH

---

all/entrypoint.sh

There is a warning when running with `-l python`:
```
$ docker run -v $PWD:/defs namely/protoc-all:1.51_2 -l python -d /defs
xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value
```
Hence we can remove the `--max-args` a.k.a. `-n` option.

Remove xargs warning for Python generation
