namely/docker-protoc

- README.md
- build.sh
- golang/Dockerfile
- push.sh
- ruby/Dockerfile
Also updates to go1.6 and makes push script a little more dynamic.
> Switches to using public docker hub

- csharp/Dockerfile
https://github.com/grpc/grpc/issues/8172
> Use our version of protoc in the grpc plugin

- README.md
Hi,
If this looks good, please squash and merge.
-Steve O
> Improve docs for Windows & put basic Docker troubleshooting info

- all/entrypoint.sh
> Remove max-depth option for directory flag.

- all/entrypoint.sh
> Only create init for python directories.

- all/entrypoint.sh
- all/test.sh
> Support java outputting to a jar.

- all/Dockerfile
- all/entrypoint.sh
We are using this to generate nicely formatted docs for our data analytics team to view.
> Add option to generate documentation

- all/entrypoint.sh
> Allow concatenating includes

- gwy/generate_gateway.sh
This handles the case where the user wants to pass along optional, extra includes to generate the gateway files.
> Add optional, extra includes for gateway generation.

- all/entrypoint.sh
* Addresses this issue for golang docker https://github.com/golang/protobuf/issues/39
* If you have subdirectories to target you will have to generate them separately.
> fixes https://github.com/golang/protobuf/issues/39

- Dockerfile
- all/entrypoint.sh
this is useful if one wants to use local versions of these protos.
> flag to not include google protos

- README.md
> Minor: fixes to readme

- all/entrypoint.sh
> Add descriptor_set_out flags to command line tool

- Dockerfile
My team would like to pick up some changes from the latest `grpc-web` release.
> Update grpc-web to 1.0.7

- Dockerfile
- all/entrypoint.sh
Added support to `go-proto-validators` from https://github.com/mwitkow/go-proto-validators
> Add support to go-proto-validators

- Dockerfile
> move arg into dockerfile

- Dockerfile
- all/entrypoint.sh
> Added missing copy from go-proto-validators

- all/test.sh
- all/test/include.proto
- all/test/test.proto
This PR adds tests  for the flags:
`--go-source-relative`
`--with-validator`
`--validator-source-relative`
> Add tests for go and validator source relative flags

- all/entrypoint.sh
- all/test.sh
- variables.sh
Add support for go module=$prefix option
See more information [here](https://developers.google.com/protocol-buffers/docs/reference/go-generated#invocation).
> Add support for go module prefix option

- .github/workflows/master.yml
- .github/workflows/pr.yml
- .github/workflows/prerelease.yml
1. Fix build step in pre release (used invalid makefile target before)
1. Ignore CI runs when pr is for master.yaml and release yamls nad vice versa.
> Fix build step in release; ignore ci run when changes are irrelevant

- all/entrypoint.sh
- all/test.sh
- all/test/all_test.go
- build.sh
- gwy/generate_gateway.sh
- gwy/test.sh
- push.sh
This should fix cases the build and/or the tests fail but the GH action does not stop/report the error.
> Force bash script to exit with failure when any command fails

- all/entrypoint.sh
- all/test/all_test.go
> Change the lang in the validator to go instead of gogo; add test
